global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "monitor"

rule_files:

scrape_configs:
  - job_name: "local"
    scrape_interval: 1s
    scheme: http
    static_configs:
      - targets: ["app:8067"]
